baseURL = "https://corgigo.github.io"
languageCode = "en-us"
title = "Discover the Best Products and Services with Cogigo's Best Lists"
theme = 'ananke'
enableRobotsTXT = true

[params]
site_logo = "img/logo.png"
read_more_copy = "Read more ..."
show_reading_time = true
description = "Corgigo is a comparison platform with curated best lists of various products and services to help you make informed decisions."
relcanonical = "https://www.corgigo.com/"
custom_css = ["table.css"]

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'

[permalinks]
  posts = "/:filename"
