baseURL = "https://corgigo.github.io"
languageCode = "en-us"
title = "The Best of Best"
theme = 'ananke'
enableRobotsTXT = true

[params]
site_logo = "img/logo.png"
read_more_copy = "Read more ..."
show_reading_time = true
description = "No More Searching: Discover the Best with Ease"
relcanonical = "https://www.corgigo.com/"

[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'

[permalinks]
  posts = "/:title"
